create dummy .env for docker compose

diff --git a/.github/workflows/mlops.yml b/.github/workflows/mlops.yml
--- a/.github/workflows/mlops.yml
+++ b/.github/workflows/mlops.yml
@@ -81,12 +81,18 @@ jobs:
           cp -r _ci_download/mlruns/* mlruns/
           chmod -R 777 mlruns
 
+      #  Create dummy .env so Docker Compose stops failing
+      - name: Create dummy .env to satisfy Docker Compose
+        run: |
+          echo "# dummy .env for docker compose" > .env
+
       # === Restart API and validate ===
       - name: Restart API
         run: |
-          docker compose --env-file /dev/null down api || true
           API_KEY=$API_KEY MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI PORT=$PORT \
-          docker compose --env-file /dev/null up -d api
+          docker compose down api || true
+          API_KEY=$API_KEY MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI PORT=$PORT \
+          docker compose up -d api
           echo "API restarted with secrets from GitHub Actions."
 
       - name: Validate API with health check
